### ISSUE TITLE
CSS3 vw实现滚动条出现页面不跳动

### ISSUE THREAD

**Issue by TinyAllen** [TinyAllen/Blog#2]
现在的很多网站都是采用水平居中的布局方式，几乎无处不在的 ```margin : 0 auto;```，但这也带来了一个小问题，就是滚动条的一出现，页面整体宽度变了，整个页面会往左跳一下，滚动条一消失它又跳回来，看着非常的不爽，Android这类的手机浏览器因为不占体积没有这种问题但是其他桌面浏览器几乎都存在。

## 解决方案

解决固定定位跳动：

``` css
.header{
  display:fixed;
  width:100vm;
}
```

解决绝对定位跳动：

``` css
.container{
  display:absolute;
  width:100vm;
}
```
整体解决方案：

``` css
html {
  overflow-y: scroll;
}

:root {
  overflow-y: auto;
  overflow-x: hidden;
}

:root body {
  position: absolute;
}

body {
  width: 100vw;
  overflow: hidden;
}
```

## css3 单位 vm

vm 是一个比较少见的单位，它相对于视窗的宽度，取决于哪个更小，**滚动条宽度也计算在内**。

100vm 就相当于整个页面窗口带滚动条的宽度。

用 100vm 可以轻松的解决宽度因滚动条出现而变化的问题。

### 兼容性：

![1](https://user-images.githubusercontent.com/19775780/27691110-aa963e98-5d15-11e7-8fb1-872fa3dee901.PNG)
